name: roo-code-cloud

services:
  postgres:
    container_name: roo-code-cloud-postgres
    image: postgres:17.5
    ports:
      - '5432:5432'
    volumes:
      - ./.docker/data/postgres:/var/lib/postgresql/data
      - ./.docker/scripts/postgres:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DATABASES=roo_code_development,roo_code_test
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d roo_code_development']
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 30s

  clickhouse:
    container_name: roo-code-cloud-clickhouse
    image: clickhouse/clickhouse-server
    ports:
      - '8123:8123'
      - '9000:9000'
    volumes:
      - ./.docker/data/clickhouse:/var/lib/clickhouse/
      - ./.docker/logs/clickhouse:/var/log/clickhouse-server/
      - ./.docker/scripts/clickhouse:/docker-entrypoint-initdb.d
    environment:
      - CLICKHOUSE_DB=default
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=password
    healthcheck:
      test: ['CMD-SHELL', 'wget --no-verbose --tries=1 --spider http://localhost:8123/ping || exit 1']
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 30s
