services:
  postgres:
    container_name: postgres
    image: postgres:15.4
    ports:
      - 5432:5432
    volumes:
      - ./.docker/postgres:/var/lib/postgresql/data
      - ./.docker/scripts/postgres:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DATABASES=roo_code_development,roo_code_test
  clickhouse:
    container_name: clickhouse
    image: clickhouse/clickhouse-server
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - ./.docker/clickhouse:/var/lib/clickhouse/
      - ./.docker/clickhouse-logs:/var/log/clickhouse-server/
      - ./.docker/scripts/clickhouse:/docker-entrypoint-initdb.d
    environment:
      - CLICKHOUSE_DB=default
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=password
